name = "PhyLearn_EN"
uuid = "810f855e-60da-4232-bec9-eecd65aaa80f"
version = "0.1.0"
authors = ["yueshang "]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15.8"
Graphs = "1.13.2"
LinearAlgebra = "1.12.0"
Plots = "1.41.2"
Pluto = "0.20.21"
Random = "1.11.0"
SimpleWeightedGraphs = "1.5.1"
StableRNGs = "1.0.4"
Statistics = "1.11.1"
