name = "PhyLearn_EN"
uuid = "810f855e-60da-4232-bec9-eecd65aaa80f"
version = "0.1.0"
authors = ["yueshang "]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.12.0"
Pluto = "0.20.21"
Random = "1.11.0"
